version: "3.3"

services:
  math-academy-api:
    container_name: math-academy-api
    restart: always
    image: node:20.19.0
    ports:
      - 4005:4000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/math-academy-api
    working_dir: /usr/src/math-academy-api
    networks:
      - math-academy-network
    depends_on:
      - postgres
    command: bash -c "rm -rf dist && npm install --include=dev && npm run build && npm run start:prod"

  postgres:
    container_name: math-academy-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: math_academy
      POSTGRES_USER: math_user
      POSTGRES_PASSWORD: math123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - math-academy-network

volumes:
  postgres_data:

networks:
  math-academy-network:
    driver: bridge
