// O'zbekiston Respublikasining ma'muriy-hududiy bo'linishi (14 viloyat/respublika + tumanlar).
// Eslatma: bu ro'yxat umumiy ma'lumotlar asosida tuzilgan — so'nggi yillarda ba'zi
// tumanlar qayta tashkil etilgan/nomlangan bo'lishi mumkin, shuning uchun kerak
// bo'lsa rasmiy manba (soliq.uz, stat.uz) bilan solishtirib to'g'irlang.

export interface UzDistrict {
  name: string;
}

export interface UzRegion {
  code: string;
  name: string;
  districts: UzDistrict[];
}

export const UZBEKISTAN_REGIONS: UzRegion[] = [
  {
    code: 'TSH_SH',
    name: 'Toshkent shahri',
    districts: [
      { name: 'Bektemir tumani' },
      { name: 'Chilonzor tumani' },
      { name: 'Mirobod tumani' },
      { name: "Mirzo Ulug'bek tumani" },
      { name: 'Olmazor tumani' },
      { name: 'Sergeli tumani' },
      { name: 'Shayxontohur tumani' },
      { name: 'Uchtepa tumani' },
      { name: 'Yakkasaroy tumani' },
      { name: 'Yangihayot tumani' },
      { name: 'Yashnobod tumani' },
      { name: 'Yunusobod tumani' },
    ],
  },
  {
    code: 'TSH_V',
    name: 'Toshkent viloyati',
    districts: [
      { name: 'Bekobod tumani' },
      { name: "Bo'ka tumani" },
      { name: "Bo'stonliq tumani" },
      { name: 'Chinoz tumani' },
      { name: 'Qibray tumani' },
      { name: 'Ohangaron tumani' },
      { name: "Oqqo'rg'on tumani" },
      { name: 'Parkent tumani' },
      { name: 'Piskent tumani' },
      { name: 'Quyichirchiq tumani' },
      { name: "O'rtachirchiq tumani" },
      { name: 'Toshkent tumani' },
      { name: "Yangiyo'l tumani" },
      { name: 'Yuqorichirchiq tumani' },
      { name: 'Zangiota tumani' },
      { name: 'Nurafshon shahri' },
    ],
  },
  {
    code: 'AND',
    name: 'Andijon viloyati',
    districts: [
      { name: 'Andijon shahri' },
      { name: 'Andijon tumani' },
      { name: 'Asaka tumani' },
      { name: 'Baliqchi tumani' },
      { name: "Bo'z tumani" },
      { name: 'Buloqboshi tumani' },
      { name: 'Izboskan tumani' },
      { name: 'Jalaquduq tumani' },
      { name: "Xo'jaobod tumani" },
      { name: "Qo'rg'ontepa tumani" },
      { name: 'Marhamat tumani' },
      { name: "Oltinko'l tumani" },
      { name: 'Paxtaobod tumani' },
      { name: 'Shahrixon tumani' },
      { name: "Ulug'nor tumani" },
      { name: 'Xonobod shahri' },
    ],
  },
  {
    code: 'FAR',
    name: "Farg'ona viloyati",
    districts: [
      { name: "Farg'ona shahri" },
      { name: "Farg'ona tumani" },
      { name: "Marg'ilon shahri" },
      { name: "Qo'qon shahri" },
      { name: "Bag'dod tumani" },
      { name: 'Beshariq tumani' },
      { name: 'Buvayda tumani' },
      { name: "Dang'ara tumani" },
      { name: 'Furqat tumani' },
      { name: "Qo'shtepa tumani" },
      { name: 'Rishton tumani' },
      { name: "So'x tumani" },
      { name: 'Toshloq tumani' },
      { name: 'Uchko‘prik tumani' },
      { name: "O'zbekiston tumani" },
      { name: 'Yozyovon tumani' },
      { name: 'Oltiariq tumani' },
    ],
  },
  {
    code: 'NAM',
    name: 'Namangan viloyati',
    districts: [
      { name: 'Namangan shahri' },
      { name: 'Namangan tumani' },
      { name: 'Kosonsoy tumani' },
      { name: 'Mingbuloq tumani' },
      { name: 'Norin tumani' },
      { name: 'Pop tumani' },
      { name: "To'raqo'rg'on tumani" },
      { name: "Uchqo'rg'on tumani" },
      { name: 'Uychi tumani' },
      { name: 'Chortoq tumani' },
      { name: 'Chust tumani' },
      { name: "Yangiqo'rg'on tumani" },
      { name: 'Davlatobod tumani' },
    ],
  },
  {
    code: 'SIR',
    name: 'Sirdaryo viloyati',
    districts: [
      { name: 'Guliston shahri' },
      { name: 'Guliston tumani' },
      { name: 'Boyovut tumani' },
      { name: 'Mirzaobod tumani' },
      { name: 'Oqoltin tumani' },
      { name: 'Sardoba tumani' },
      { name: 'Sayxunobod tumani' },
      { name: 'Sirdaryo tumani' },
      { name: 'Xovos tumani' },
      { name: 'Shirin shahri' },
    ],
  },
  {
    code: 'JIZ',
    name: 'Jizzax viloyati',
    districts: [
      { name: 'Jizzax shahri' },
      { name: 'Jizzax tumani' },
      { name: 'Arnasoy tumani' },
      { name: 'Baxmal tumani' },
      { name: "Do'stlik tumani" },
      { name: 'Forish tumani' },
      { name: "G'allaorol tumani" },
      { name: "Mirzacho'l tumani" },
      { name: 'Paxtakor tumani' },
      { name: 'Zomin tumani' },
      { name: 'Zafarobod tumani' },
      { name: 'Zarbdor tumani' },
    ],
  },
  {
    code: 'SAM',
    name: 'Samarqand viloyati',
    districts: [
      { name: 'Samarqand shahri' },
      { name: 'Samarqand tumani' },
      { name: 'Bulung‘ur tumani' },
      { name: 'Ishtixon tumani' },
      { name: 'Jomboy tumani' },
      { name: "Kattaqo'rg'on shahri" },
      { name: "Kattaqo'rg'on tumani" },
      { name: 'Narpay tumani' },
      { name: 'Nurobod tumani' },
      { name: 'Oqdaryo tumani' },
      { name: 'Payariq tumani' },
      { name: 'Pastdarg‘om tumani' },
      { name: 'Paxtachi tumani' },
      { name: 'Toyloq tumani' },
      { name: 'Urgut tumani' },
      { name: "Qo'shrabot tumani" },
    ],
  },
  {
    code: 'BUX',
    name: 'Buxoro viloyati',
    districts: [
      { name: 'Buxoro shahri' },
      { name: 'Buxoro tumani' },
      { name: 'Kogon shahri' },
      { name: 'Kogon tumani' },
      { name: 'Vobkent tumani' },
      { name: "G'ijduvon tumani" },
      { name: 'Jondor tumani' },
      { name: "Qorako'l tumani" },
      { name: 'Qorovulbozor tumani' },
      { name: 'Peshku tumani' },
      { name: 'Romitan tumani' },
      { name: 'Shofirkon tumani' },
      { name: 'Olot tumani' },
    ],
  },
  {
    code: 'NAV',
    name: 'Navoiy viloyati',
    districts: [
      { name: 'Navoiy shahri' },
      { name: 'Zarafshon shahri' },
      { name: 'Konimex tumani' },
      { name: 'Karmana tumani' },
      { name: 'Xatirchi tumani' },
      { name: 'Navbahor tumani' },
      { name: 'Nurota tumani' },
      { name: 'Qiziltepa tumani' },
      { name: 'Tomdi tumani' },
      { name: "Uchquduq tumani" },
    ],
  },
  {
    code: 'QAS',
    name: 'Qashqadaryo viloyati',
    districts: [
      { name: 'Qarshi shahri' },
      { name: 'Qarshi tumani' },
      { name: 'Shahrisabz shahri' },
      { name: 'Shahrisabz tumani' },
      { name: "G'uzor tumani" },
      { name: 'Dehqonobod tumani' },
      { name: 'Kasbi tumani' },
      { name: 'Kitob tumani' },
      { name: 'Koson tumani' },
      { name: 'Mirishkor tumani' },
      { name: 'Muborak tumani' },
      { name: 'Nishon tumani' },
      { name: 'Qamashi tumani' },
      { name: 'Chiroqchi tumani' },
      { name: "Yakkabog' tumani" },
    ],
  },
  {
    code: 'SUR',
    name: 'Surxondaryo viloyati',
    districts: [
      { name: 'Termiz shahri' },
      { name: 'Termiz tumani' },
      { name: 'Angor tumani' },
      { name: 'Bandixon tumani' },
      { name: 'Boysun tumani' },
      { name: 'Denov tumani' },
      { name: "Jarqo'rg'on tumani" },
      { name: 'Muzrabot tumani' },
      { name: 'Oltinsoy tumani' },
      { name: 'Sariosiyo tumani' },
      { name: "Sherobod tumani" },
      { name: "Sho'rchi tumani" },
      { name: 'Uzun tumani' },
      { name: 'Qiziriq tumani' },
      { name: "Qumqo'rg'on tumani" },
    ],
  },
  {
    code: 'XOR',
    name: 'Xorazm viloyati',
    districts: [
      { name: 'Urganch shahri' },
      { name: 'Urganch tumani' },
      { name: 'Xiva shahri' },
      { name: 'Xiva tumani' },
      { name: "Bog'ot tumani" },
      { name: 'Gurlan tumani' },
      { name: 'Hazorasp tumani' },
      { name: 'Xonqa tumani' },
      { name: "Qo'shko'pir tumani" },
      { name: 'Shovot tumani' },
      { name: 'Yangiariq tumani' },
      { name: 'Yangibozor tumani' },
    ],
  },
  {
    code: 'QOR',
    name: "Qoraqalpog'iston Respublikasi",
    districts: [
      { name: 'Nukus shahri' },
      { name: 'Nukus tumani' },
      { name: 'Amudaryo tumani' },
      { name: 'Beruniy tumani' },
      { name: 'Chimboy tumani' },
      { name: "Ellikqal'a tumani" },
      { name: 'Kegeyli tumani' },
      { name: "Mo'ynoq tumani" },
      { name: "Qanliko'l tumani" },
      { name: "Qo'ng'irot tumani" },
      { name: "Qorao'zak tumani" },
      { name: 'Shumanay tumani' },
      { name: 'Taxtako‘pir tumani' },
      { name: "To'rtko'l tumani" },
      { name: "Xo'jayli tumani" },
    ],
  },
];

export function findRegionByCode(code: string): UzRegion | undefined {
  return UZBEKISTAN_REGIONS.find((r) => r.code === code);
}
